In [2]:
'''
Импортируйте модуль numpy как np
'''

import numpy as np

In [6]:
'''
Выведите на печать версию модуля numpy, используемую в текущий момент в песочнице Stepik.
'''

print(np.__version__)
print(np.version.version)

1.19.2
1.19.2


In [10]:
'''
Считайте число n

Создайте в переменной Z Numpy вектор из нулей длины n.
'''

Z = np.zeros(int(input()))
Z

array([0., 0., 0., 0., 0.])

In [33]:
'''
Считайте строку, где значения заданы через пробел shape и dtype

Последнее значение в строке может быть либо числом (тогда это последнее значение кортежа shape, либо строкой dtype)

shape - атрибут, задающий размеры матрицы нолей (позволяет вернуть вектор-строку, вектор-столбец, матрицу, куб и т.д.)
dtype - тип данных, использующихся для значений матрицы. По-умолчанию используется numpy.float64.
Создайте матрицу Z размера shape, со значениями типа dtype (если dtype не указан, используйте numpy.float64)
'''

shape = input().split()
if shape[-1].isalpha():
    Z = np.zeros(tuple(map(int, shape[:-1])), dtype=shape[-1])
else:
    Z = np.zeros(tuple(map(int, shape)))

Z

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [37]:
'''
Посчитайте размер матрицы Z в байтах и выведите его на печать.
'''

Z = np.array([1,2,3], dtype=np.float64)
print(Z.itemsize * Z.size)

24


In [42]:
'''
Выведите на печать встроенную документацию для функции add numpy, а потом объекта numpy.array
'''

#np.info(np.add)
#np.info(np.array)

'\nВыведите на печать встроенную документацию для функции add numpy, а потом объекта numpy.array\n'

In [44]:
'''
Считайте 2 числа:

n - размер Numpy вектора
x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора должны быть равны 0.
Сохраните вектор в переменную Z.
'''

n, x = int(input()), int(input())
Z = np.zeros(n)
Z[x] = 1
Z

array([0., 1., 0., 0.])

In [49]:
'''
Считайте 2 числа n, m.

Создайте вектор Z состоящий из чисел от n до m с шагом 1.
'''

n, m = int(input()), int(input())
Z = np.arange(n, m+1)
Z

array([ 5,  6,  7,  8,  9, 10])

In [63]:
'''
Дан вектор Z

"Разверните" его.
'''

Z = np.array([1, 2, 3, 4])
Z = Z[::-1]
Z

array([4, 3, 2, 1])

In [70]:
'''
Считайте 3 числа:

n - количество элементов матрицы
m и k - размеры матрицы (число строк и столбцов соответственно)
Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).

Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется пустых мест.
'''

n = int(input())
m, k = map(int, input().split())
Z = np.arange(n).reshape((m, k))
Z

array([[0, 1, 2],
       [3, 4, 5]])

In [78]:
'''
Дан вектор Z

Запишите в переменную NonZerros индексы ненулевых элементов.
'''

Z = np.array([1, 0, 2, 0, 3, 0, 4])
NonZerros = np.nonzero(Z)
NonZerros

(array([0, 2, 4, 6], dtype=int64),)

In [82]:
'''
Дана матрица чисел Z (Z может быть 1, 2 или даже 3 мерной).

Выведите на печать список чисел из этой матрицы, которые больше 3.
'''

Z = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [0, 0, 9]])

print(list(Z[Z>3]))

[4, 5, 6, 7, 8, 9, 9]


In [3]:
'''
Считайте число n

Создайте единичную матрицу размера n, сохраните результат в переменную Z.
'''

n = int(input())
Z = np.eye(n)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
'''
Считайте 3 числа: n, m, l.

Зафиксируйте значение генератора случайных чисел Numpy с помощью numpy.random.seed(42)
Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и сохраните результат в переменную Z.
'''

n, m, l = map(int, input().split())
np.random.seed(42)
Z = np.random.random((n, m, l))
Z

array([[[0.37454012, 0.95071431],
        [0.73199394, 0.59865848]],

       [[0.15601864, 0.15599452],
        [0.05808361, 0.86617615]]])

In [7]:
'''
Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)
Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение минимального и максимального чисел в получившейся матрице (каждое с новой строки).
'''

n, m = map(int, input().split())
np.random.seed(42)
M = np.random.random((n, m))
print(np.min(M), np.max(M), sep='\n')

0.005522117123602399
0.9868869366005173


In [9]:
'''
Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)
Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение среднего для всей матрицы.
'''

n, m = map(int, input().split())
np.random.seed(42)
M = np.random.random((n, m))
print(np.mean(M))

0.4923750160905882


In [15]:
'''
Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)
Создайте матрицу n*m из случайных чисел (от 0 до 1).
Найдите среднее значение для каждого из столбцов.
Выведите на печать значение минимального и максимального среднего по столбцам (каждое с новой строки).
'''

n, m = map(int, input().split())
np.random.seed(42)
avg = np.random.random((n, m)).mean(axis=0)
print(np.min(avg), np.max(M), sep='\n')

0.270220682758469
0.8115814940446553


In [20]:
'''
Считайте 2 числа: n, m.

Создайте матрицу размера n*m такую что:
На границе матрицы будут стоять 1
Внутри матрицы будут стоять 0
Сохраните матрицу в переменную Z.
'''

n, m = map(int, input().split())
Z = np.ones((n, m))
Z[1:-1, 1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
'''
Имеется матрица Z
Добавьте вокруг имеющихся значений матрицы "забор" из 0.
'''

Z = np.ones((5, 5))
M = np.zeros(np.array(Z.shape)+2, dtype=int)
M[1:-1, 1:-1] = Z
Z = M
Z

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [34]:
Z = np.ones((5, 5))
Z = np.pad(Z, 1)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [37]:
n = np.nan
m = np.nan
print(id(n), id(m), sep='\n')
print(id(n) == id(m))
print(n == m)

2820205712304
2820205712304
True
False


In [38]:
print(n - m)
print(0.3 == 3 * 0.1)
print(n == m)
print(0 * n)
print(np.isnan(n))
print(np.inf > n)
print(n in set([m]))

nan
False
False
nan
True
False
True


In [42]:
'''
Считайте число n.

Создайте диагональную матрицу размера n*n. На главной диагонали должны быть числа от 1 до n.
Сохраните матрицу в переменную Z.
'''

n = int(input())
v = np.arange(n) + 1
Z = np.diag(v)
v, Z

(array([1, 2, 3, 4, 5]),
 array([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]]))

In [48]:
'''
Считайте 2 числа:

x - сдвиг для единственной ненулевой диагонали в матрице.
k - верхняя граница для интервала чисел на диагонали (т.е. если k = 5, то на диагонали будут стоять числа 1, 2, 3, 4 и 5)
Договоримся о значениях x:

x = 0 - это главная диагональ матрицы
x<0 - диагональ сдвигается вниз на |x| ячеек (если x = -1, то первая не нулевая ячейка будет с координатами (1,0))
x>0 - диагональ сдвигается вправо на |x| ячеек (если x = 1, то первая ненулевая ячейка будет с координатами (0,1))
'''

k, x = map(int, input().split())
Z = np.diag(np.arange(1, x+1), k)
Z

array([[0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [52]:
'''
Считайте 2 числа: n, m.
Создайте матрицу размера n*m и "раскрасьте" её в шахматную раскраску.
0 - "чёрное"
1 - "белое"
Ячейка с координатами (0, 0) всегда "чёрная" (т.е. элемент (0, 0) равен 0).
Матрицу сохраните в переменную Z.
'''

n, m = map(int, input().split())
Z = np.ones((n, m))
Z[::2, ::2] = 0
Z[1::2, 1::2] = 0
Z


array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

In [55]:
'''
Даны:

индекс i
numpy массив Z
Определите "координаты" элемента с индексом i в Z и выведите кортеж с координатами на печать.
'''
i = 7
print(np.unravel_index(i, Z.shape))

(1, 2)
