In [1]:
'''
Импортируйте модуль numpy как np
'''

import numpy as np

In [6]:
'''
Выведите на печать версию модуля numpy, используемую в текущий момент в песочнице Stepik.
'''

print(np.__version__)
print(np.version.version)

1.19.2
1.19.2


In [10]:
'''
Считайте число n

Создайте в переменной Z Numpy вектор из нулей длины n.
'''

Z = np.zeros(int(input()))
Z

array([0., 0., 0., 0., 0.])

In [33]:
'''
Считайте строку, где значения заданы через пробел shape и dtype

Последнее значение в строке может быть либо числом (тогда это последнее значение кортежа shape, либо строкой dtype)

shape - атрибут, задающий размеры матрицы нолей (позволяет вернуть вектор-строку, вектор-столбец, матрицу, куб и т.д.)
dtype - тип данных, использующихся для значений матрицы. По-умолчанию используется numpy.float64.
Создайте матрицу Z размера shape, со значениями типа dtype (если dtype не указан, используйте numpy.float64)
'''

shape = input().split()
if shape[-1].isalpha():
    Z = np.zeros(tuple(map(int, shape[:-1])), dtype=shape[-1])
else:
    Z = np.zeros(tuple(map(int, shape)))

Z

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [37]:
'''
Посчитайте размер матрицы Z в байтах и выведите его на печать.
'''

Z = np.array([1,2,3], dtype=np.float64)
print(Z.itemsize * Z.size)

24


In [42]:
'''
Выведите на печать встроенную документацию для функции add numpy, а потом объекта numpy.array
'''

#np.info(np.add)
#np.info(np.array)

'\nВыведите на печать встроенную документацию для функции add numpy, а потом объекта numpy.array\n'

In [44]:
'''
Считайте 2 числа:

n - размер Numpy вектора
x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора должны быть равны 0.
Сохраните вектор в переменную Z.
'''

n, x = int(input()), int(input())
Z = np.zeros(n)
Z[x] = 1
Z

array([0., 1., 0., 0.])

In [49]:
'''
Считайте 2 числа n, m.

Создайте вектор Z состоящий из чисел от n до m с шагом 1.
'''

n, m = int(input()), int(input())
Z = np.arange(n, m+1)
Z

array([ 5,  6,  7,  8,  9, 10])

In [63]:
'''
Дан вектор Z

"Разверните" его.
'''

Z = np.array([1, 2, 3, 4])
Z = Z[::-1]
Z

array([4, 3, 2, 1])

In [70]:
'''
Считайте 3 числа:

n - количество элементов матрицы
m и k - размеры матрицы (число строк и столбцов соответственно)
Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).

Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется пустых мест.
'''

n = int(input())
m, k = map(int, input().split())
Z = np.arange(n).reshape((m, k))
Z

array([[0, 1, 2],
       [3, 4, 5]])

In [78]:
'''
Дан вектор Z

Запишите в переменную NonZerros индексы ненулевых элементов.
'''

Z = np.array([1, 0, 2, 0, 3, 0, 4])
NonZerros = np.nonzero(Z)
NonZerros

(array([0, 2, 4, 6], dtype=int64),)

In [82]:
'''
Дана матрица чисел Z (Z может быть 1, 2 или даже 3 мерной).

Выведите на печать список чисел из этой матрицы, которые больше 3.
'''

Z = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [0, 0, 9]])

print(list(Z[Z>3]))

[4, 5, 6, 7, 8, 9, 9]


In [3]:
'''
Считайте число n

Создайте единичную матрицу размера n, сохраните результат в переменную Z.
'''

n = int(input())
Z = np.eye(n)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
'''
Считайте 3 числа: n, m, l.

Зафиксируйте значение генератора случайных чисел Numpy с помощью numpy.random.seed(42)
Создайте матрицу n*m*l из случайных чисел (от 0 до 1) и сохраните результат в переменную Z.
'''

n, m, l = map(int, input().split())
np.random.seed(42)
Z = np.random.random((n, m, l))
Z

array([[[0.37454012, 0.95071431],
        [0.73199394, 0.59865848]],

       [[0.15601864, 0.15599452],
        [0.05808361, 0.86617615]]])

In [7]:
'''
Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)
Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение минимального и максимального чисел в получившейся матрице (каждое с новой строки).
'''

n, m = map(int, input().split())
np.random.seed(42)
M = np.random.random((n, m))
print(np.min(M), np.max(M), sep='\n')

0.005522117123602399
0.9868869366005173


In [9]:
'''
Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)
Создайте матрицу n*m из случайных чисел (от 0 до 1).
Выведите на печать значение среднего для всей матрицы.
'''

n, m = map(int, input().split())
np.random.seed(42)
M = np.random.random((n, m))
print(np.mean(M))

0.4923750160905882


In [15]:
'''
Считайте 2 числа: n, m.

Зафиксируйте значение генератора случайных чисел Numpy с помощью

numpy.random.seed(42)
Создайте матрицу n*m из случайных чисел (от 0 до 1).
Найдите среднее значение для каждого из столбцов.
Выведите на печать значение минимального и максимального среднего по столбцам (каждое с новой строки).
'''

n, m = map(int, input().split())
np.random.seed(42)
avg = np.random.random((n, m)).mean(axis=0)
print(np.min(avg), np.max(M), sep='\n')

0.270220682758469
0.8115814940446553


In [20]:
'''
Считайте 2 числа: n, m.

Создайте матрицу размера n*m такую что:
На границе матрицы будут стоять 1
Внутри матрицы будут стоять 0
Сохраните матрицу в переменную Z.
'''

n, m = map(int, input().split())
Z = np.ones((n, m))
Z[1:-1, 1:-1] = 0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
'''
Имеется матрица Z
Добавьте вокруг имеющихся значений матрицы "забор" из 0.
'''

Z = np.ones((5, 5))
M = np.zeros(np.array(Z.shape)+2, dtype=int)
M[1:-1, 1:-1] = Z
Z = M
Z

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [34]:
Z = np.ones((5, 5))
Z = np.pad(Z, 1)
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [37]:
n = np.nan
m = np.nan
print(id(n), id(m), sep='\n')
print(id(n) == id(m))
print(n == m)

2820205712304
2820205712304
True
False


In [38]:
print(n - m)
print(0.3 == 3 * 0.1)
print(n == m)
print(0 * n)
print(np.isnan(n))
print(np.inf > n)
print(n in set([m]))

nan
False
False
nan
True
False
True


In [42]:
'''
Считайте число n.

Создайте диагональную матрицу размера n*n. На главной диагонали должны быть числа от 1 до n.
Сохраните матрицу в переменную Z.
'''

n = int(input())
v = np.arange(n) + 1
Z = np.diag(v)
v, Z

(array([1, 2, 3, 4, 5]),
 array([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]]))

In [48]:
'''
Считайте 2 числа:

x - сдвиг для единственной ненулевой диагонали в матрице.
k - верхняя граница для интервала чисел на диагонали (т.е. если k = 5, то на диагонали будут стоять числа 1, 2, 3, 4 и 5)
Договоримся о значениях x:

x = 0 - это главная диагональ матрицы
x<0 - диагональ сдвигается вниз на |x| ячеек (если x = -1, то первая не нулевая ячейка будет с координатами (1,0))
x>0 - диагональ сдвигается вправо на |x| ячеек (если x = 1, то первая ненулевая ячейка будет с координатами (0,1))
'''

k, x = map(int, input().split())
Z = np.diag(np.arange(1, x+1), k)
Z

array([[0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 5],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [52]:
'''
Считайте 2 числа: n, m.
Создайте матрицу размера n*m и "раскрасьте" её в шахматную раскраску.
0 - "чёрное"
1 - "белое"
Ячейка с координатами (0, 0) всегда "чёрная" (т.е. элемент (0, 0) равен 0).
Матрицу сохраните в переменную Z.
'''

n, m = map(int, input().split())
Z = np.ones((n, m))
Z[::2, ::2] = 0
Z[1::2, 1::2] = 0
Z


array([[0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.]])

In [55]:
'''
Даны:

индекс i
numpy массив Z
Определите "координаты" элемента с индексом i в Z и выведите кортеж с координатами на печать.
'''
i = 7
print(np.unravel_index(i, Z.shape))

(1, 2)


In [9]:
'''
Используйте формулу x_{new} =
где
\muμ - среднее значение (по всей матрице)
\sigmaσ - стандартное отклонение (по всей матрице)
для того чтобы "нормализовать" матрицу.
Переменная Y содержит исходную матрицу

В переменную Z сохраните её "нормализованный" вид, округлив каждое значение в матрице до 2 знака после запятой с помощью numpy.around.
'''

Y = np.array([
    [99, 11, 55],
    [33, 66, 99]
])

Z = np.around((Y - Y.mean()) / Y.std(), 2)
Z

array([[ 1.19, -1.54, -0.17],
       [-0.85,  0.17,  1.19]])

In [12]:
'''
Переменные A и B содержат по numpy вектору. Найдите их скалярное произведение и сохраните в переменную Z.

A и B могут содержать как int, так и float.
'''

A = np.array([1.5, 2.5, 3.5])
B = np.array([4, 5, 6])

Z = np.dot(A, B)
Z

39.5

In [17]:
'''
Даны 2 матрицы: A и B.

Найдите произведение матриц и сохраните его в переменную Z.

Если найти произведение матриц невозможно, то запишите в Z строку:

Упс! Что-то пошло не так...
'''

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
B = np.array([
    [11.5],
    [12.5],
    #[12.5],
    [13.5]
])
try:
    Z = A @ B
except ValueError:
    Z = 'Упс! Что-то пошло не так...'
Z

array([[ 77. ],
       [189.5]])

In [26]:
'''
Поменяйте знак всех чисел из интервала (3; 9), хранящихся в векторе Z.
'''

Z = np.arange(11)

Z[(Z>3) & (Z<9)] *= -1
Z

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

In [40]:
z = np.array([1, 2, 3, 4, 5, 6, 7])
1j*z

array([0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j])

In [43]:
np.array(0)/np.array(0), np.array(0)//np.array(0), np.array([np.nan]).astype(int).astype(float)

(nan, 0, array([-2.14748365e+09]))

In [60]:
'''
Вектор A содержит float числа как больше, так и меньше нуля.

Округлите их до целых и результат запишите в переменную Z. Округление должно быть "от нуля", т.е.:

положительные числа округляем всегда вверх до целого
отрицательные числа округляем всегда вниз до целого
0 остаётся 0
'''

A = np.array([-3.1, -5.9, 0, 2.2, 9.8])

Z = np.copysign(np.ceil(np.abs(A)), A)
Z

array([-4., -6.,  0.,  3., 10.])

In [73]:
'''
Даны 2 вектора целых чисел A и B.

Найдите числа, встречающиеся в обоих векторах и составьте их по возрастанию в вектор Z.

Если пересечений нет, то вектор Z будет пустым.
'''

A = np.array([0, 9, 7, 1, 3, 7, 5, 2, 5, 1])
B = np.array([3, 1, 3, 7, 4, 1, 8, 1, 1, 8])

Z = np.sort(np.intersect1d(A, B))
Z

array([1, 3, 7])

In [5]:
'''
В Numpy можно предусмотреть различное поведение в случае ошибок (а не только то, что мы наблюдали в задаче 28). Для этого используется функция https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.seterr.html

Отключите вывод всех ошибок (это довольно опасное поведение)
'''

np.seterr('ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [6]:
old_settings = {'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
np.seterr(**old_settings)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [9]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [17]:
'''
1-я входная строка - год (опционально месяц и день) в формате ISO начала отсчёта
2-я входная строка - год (опционально месяц и день) в формате ISO окончания отсчёта
Составьте список (numpy array) дат с шагом в 1 день от начала до окончания отсчёта (последний день не включается).
Результат должен представлять из себя список дат в формате ISO.
Пример - 2005-02-25, где

2005 - год
02 - месяц
25 - день
Запишите результат в переменную Z
'''

start = np.datetime64(input(), 'D')
end = np.datetime64(input(), 'D')
Z = np.arange(start, end)
Z

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08'],
      dtype='datetime64[D]')

In [16]:
Z = np.arange(input(), input(), dtype='datetime64[D]')
Z

array(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
       '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08'],
      dtype='datetime64[D]')