In [1]:
'''
На вход подаётся список чисел (строка, где числа разделены запятой).

Создайте и сохраните:

в переменную V1 Numpy вектор из этих чисел в том же порядке
в переменную V2 Numpy вектор, содержащий только предпоследнее число (это должен быть именно вектор!)
в переменную V3 Numpy вектор из этих чисел в обратном порядке
в переменную V4 Numpy вектор из этих чисел, начиная с 0-ого, через 2 (т.е. каждое третье число)
в переменную V5 Numpy вектор, созданный из генератора Range, содержащий столько элементов, сколько было передано чисел на вход
'''

import numpy as np

V = list(map(float, input().split(', ')))

V1 = np.array(V)
V2 = np.array(V[-2])
V3 = np.array(V[::-1])
V4 = np.array(V[::3])
V5 = np.array(range(len(V)))

In [5]:
'''
На вход подаётся 2 списка целых чисел (они представляют из себя вектора равной длины, т.е. с одинаковым количеством элементов).

Используя векторные операции создайте и сохраните:

в переменную V1 Numpy вектор с числами из 1 строки
в переменную V2 Numpy вектор с числами из 2 строки
в переменную V3 Numpy вектор с покоординатными суммами V1 и V2
в переменную V4 Numpy вектор с покоординатными произведениями каждого второго числа V1 на каждое второе число V2, развёрнутого в обратном порядке
'''

import numpy as np

V1, V2 = (np.array(list(map(int, input().split(', ')))) for _ in range(2))
V3 = V1 + V2
V4 = V1[::2] * V2[::-2]

V1, V2, V3, V4

(array([1, 2, 3, 4]),
 array([10, 20, 30, 40]),
 array([11, 22, 33, 44]),
 array([40, 60]))

In [7]:
import numpy as np

V1, V2 = (np.fromstring(input(), dtype=np.int, sep=', ') for _ in range(2))
V3 = V1 + V2
V4 = V1[::2] * V2[::-1][::2]

V1, V2, V3, V4

(array([1, 2, 3]), array([50, 20, 40]), array([51, 22, 43]), array([ 40, 150]))