In [1]:
'''
Импортируйте модуль numpy как np
'''

import numpy as np

In [6]:
'''
Выведите на печать версию модуля numpy, используемую в текущий момент в песочнице Stepik.
'''

print(np.__version__)
print(np.version.version)

1.19.2
1.19.2


In [10]:
'''
Считайте число n

Создайте в переменной Z Numpy вектор из нулей длины n.
'''

Z = np.zeros(int(input()))
Z

array([0., 0., 0., 0., 0.])

In [33]:
'''
Считайте строку, где значения заданы через пробел shape и dtype

Последнее значение в строке может быть либо числом (тогда это последнее значение кортежа shape, либо строкой dtype)

shape - атрибут, задающий размеры матрицы нолей (позволяет вернуть вектор-строку, вектор-столбец, матрицу, куб и т.д.)
dtype - тип данных, использующихся для значений матрицы. По-умолчанию используется numpy.float64.
Создайте матрицу Z размера shape, со значениями типа dtype (если dtype не указан, используйте numpy.float64)
'''

shape = input().split()
if shape[-1].isalpha():
    Z = np.zeros(tuple(map(int, shape[:-1])), dtype=shape[-1])
else:
    Z = np.zeros(tuple(map(int, shape)))

Z

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [37]:
'''
Посчитайте размер матрицы Z в байтах и выведите его на печать.
'''

Z = np.array([1,2,3], dtype=np.float64)
print(Z.itemsize * Z.size)

24


In [42]:
'''
Выведите на печать встроенную документацию для функции add numpy, а потом объекта numpy.array
'''

#np.info(np.add)
#np.info(np.array)

'\nВыведите на печать встроенную документацию для функции add numpy, а потом объекта numpy.array\n'

In [44]:
'''
Считайте 2 числа:

n - размер Numpy вектора
x - координата элемента вектора, который должен быть равен 1. Остальные элементы вектора должны быть равны 0.
Сохраните вектор в переменную Z.
'''

n, x = int(input()), int(input())
Z = np.zeros(n)
Z[x] = 1
Z

array([0., 1., 0., 0.])

In [49]:
'''
Считайте 2 числа n, m.

Создайте вектор Z состоящий из чисел от n до m с шагом 1.
'''

n, m = int(input()), int(input())
Z = np.arange(n, m+1)
Z

array([ 5,  6,  7,  8,  9, 10])

In [63]:
'''
Дан вектор Z

"Разверните" его.
'''

Z = np.array([1, 2, 3, 4])
Z = Z[::-1]
Z

array([4, 3, 2, 1])

In [70]:
'''
Считайте 3 числа:

n - количество элементов матрицы
m и k - размеры матрицы (число строк и столбцов соответственно)
Заполните матрицу Z числами от 0 до n-1 по порядку (сперва строки, потом столбцы).

Гарантируется, что m*k = n, т.е. все элементы "влезут" в матрицу и не останется пустых мест.
'''

n = int(input())
m, k = map(int, input().split())
Z = np.arange(n).reshape((m, k))
Z

array([[0, 1, 2],
       [3, 4, 5]])

In [78]:
'''
Дан вектор Z

Запишите в переменную NonZerros индексы ненулевых элементов.
'''

Z = np.array([1, 0, 2, 0, 3, 0, 4])
NonZerros = np.nonzero(Z)
NonZerros

(array([0, 2, 4, 6], dtype=int64),)

In [82]:
'''
Дана матрица чисел Z (Z может быть 1, 2 или даже 3 мерной).

Выведите на печать список чисел из этой матрицы, которые больше 3.
'''

Z = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9],
          [0, 0, 9]])

print(list(Z[Z>3]))

[4, 5, 6, 7, 8, 9, 9]
