In [1]:
'''
На вход подаётся список чисел (строка, где числа разделены запятой).

Создайте и сохраните:

в переменную V1 Numpy вектор из этих чисел в том же порядке
в переменную V2 Numpy вектор, содержащий только предпоследнее число (это должен быть именно вектор!)
в переменную V3 Numpy вектор из этих чисел в обратном порядке
в переменную V4 Numpy вектор из этих чисел, начиная с 0-ого, через 2 (т.е. каждое третье число)
в переменную V5 Numpy вектор, созданный из генератора Range, содержащий столько элементов, сколько было передано чисел на вход
'''

import numpy as np

V = list(map(float, input().split(', ')))

V1 = np.array(V)
V2 = np.array(V[-2])
V3 = np.array(V[::-1])
V4 = np.array(V[::3])
V5 = np.array(range(len(V)))

In [5]:
'''
На вход подаётся 2 списка целых чисел (они представляют из себя вектора равной длины, т.е. с одинаковым количеством элементов).

Используя векторные операции создайте и сохраните:

в переменную V1 Numpy вектор с числами из 1 строки
в переменную V2 Numpy вектор с числами из 2 строки
в переменную V3 Numpy вектор с покоординатными суммами V1 и V2
в переменную V4 Numpy вектор с покоординатными произведениями каждого второго числа V1 на каждое второе число V2, развёрнутого в обратном порядке
'''

import numpy as np

V1, V2 = (np.array(list(map(int, input().split(', ')))) for _ in range(2))
V3 = V1 + V2
V4 = V1[::2] * V2[::-2]

V1, V2, V3, V4

(array([1, 2, 3, 4]),
 array([10, 20, 30, 40]),
 array([11, 22, 33, 44]),
 array([40, 60]))

In [7]:
import numpy as np

V1, V2 = (np.fromstring(input(), dtype=np.int, sep=', ') for _ in range(2))
V3 = V1 + V2
V4 = V1[::2] * V2[::-1][::2]

V1, V2, V3, V4

(array([1, 2, 3]), array([50, 20, 40]), array([51, 22, 43]), array([ 40, 150]))

In [11]:
'''
На вход подаётся 2 набора целых чисел.

Создайте вектор V такой, что он будет содержать числа из 1 набора, делящиеся нацело на предпоследнее число из 2 набора и разделённые на это число.

Если таких чисел не найдётся, то вектор V будет пустым (т.е. не будет содержать элементов).
'''

import numpy as np

a, b = (np.fromstring(input(), dtype=np.int, sep=', ') for _ in range(2))
V = a[a % b[-2] == 0] / b[-2]
a, b, V

(array([1, 2, 3, 4, 5, 6]), array([2, 8]), array([1., 2., 3.]))

In [20]:
'''

'''

import numpy as np

A1 = np.array((-1, 1))
A2 = np.array((2, 5))
A3 = np.array((5, -3))

a = np.sum((A1-A2)**2) ** 0.5
b = np.sum((A2-A3)**2) ** 0.5
c = np.sum((A3-A1)**2) ** 0.5
p = (a + b + c) / 2

print((p * (p-a) * (p-b) * (p-c))**0.5)
a, b, c, p

17.999999999999993


(5.0, 8.54400374531753, 7.211102550927978, 10.377553148122754)

In [23]:
'''
Переменная M1 содержит Numpy матрицу.

Произведите операции последовательно:

1. Замените значения в предпоследней строке на значения по формуле:

\LARGE sin(\frac{x \cdot \pi}{6})sin(6x⋅π), где x - старое значение
2. Замените значения в предпоследнем столбце на значения по формуле:
\LARGE e^xe 
Результат запишите в переменную M2
'''

import numpy as np

M1 = np.array((
    (1., 2., 3., 0.),
    (4., 5., 6., 0.),
    (0., 1., 1., 6.),
    (7., 8., 9., 0.)
))

M2 = M1.copy()
M2[-2] = np.sin(M1[-2] * np.pi / 6)
M2[:, -2] = np.exp(M1[:, -2])
M1, M2

(array([[1., 2., 3., 0.],
        [4., 5., 6., 0.],
        [0., 1., 1., 6.],
        [7., 8., 9., 0.]]),
 array([[1.00000000e+00, 2.00000000e+00, 2.00855369e+01, 0.00000000e+00],
        [4.00000000e+00, 5.00000000e+00, 4.03428793e+02, 0.00000000e+00],
        [0.00000000e+00, 5.00000000e-01, 2.71828183e+00, 1.22464680e-16],
        [7.00000000e+00, 8.00000000e+00, 8.10308393e+03, 0.00000000e+00]]))